# ⚠️ IMPORTANT: Do not run Docker and local dev servers simultaneously!
# This causes port conflicts and Module Federation issues.
# Choose one: Either "docker-compose up" OR local "npm start" commands.

services:
  shell:
    container_name: adip-ui-parent
    build:
      context: ./mfe-shell
      dockerfile: ../Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./mfe-shell:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    networks:
      - mfe-network
    depends_on:
      - dashboard
      - adm
      - administration
      - agis
      - amr
      - ram
      - rim
      - mos

  dashboard:
    container_name: adip-ui-dashboard
    build:
      context: ./mfe-dashboard
      dockerfile: ../Dockerfile
    ports:
      - "4100:4100"
    volumes:
      - ./mfe-dashboard:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4100
    networks:
      - mfe-network

  adm:
    container_name: adip-ui-adm
    build:
      context: ./mfe-adm
      dockerfile: ../Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./mfe-adm:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4200
    networks:
      - mfe-network

  administration:
    container_name: adip-ui-administration
    build:
      context: ./mfe-administration
      dockerfile: ../Dockerfile
    ports:
      - "4300:4300"
    volumes:
      - ./mfe-administration:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4300
    networks:
      - mfe-network

  agis:
    container_name: adip-ui-agis
    build:
      context: ./mfe-agis
      dockerfile: ../Dockerfile
    ports:
      - "4400:4400"
    volumes:
      - ./mfe-agis:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4400
    networks:
      - mfe-network

  amr:
    container_name: adip-ui-amr
    build:
      context: ./mfe-amr
      dockerfile: ../Dockerfile
    ports:
      - "4500:4500"
    volumes:
      - ./mfe-amr:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4500
    networks:
      - mfe-network

  ram:
    container_name: adip-ui-ram
    build:
      context: ./mfe-ram
      dockerfile: ../Dockerfile
    ports:
      - "4600:4600"
    volumes:
      - ./mfe-ram:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4600
    networks:
      - mfe-network

  rim:
    container_name: adip-ui-rim
    build:
      context: ./mfe-rim
      dockerfile: ../Dockerfile
    ports:
      - "4700:4700"
    volumes:
      - ./mfe-rim:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4700
    networks:
      - mfe-network

  mos:
    container_name: adip-ui-mos
    build:
      context: ./mfe-mos
      dockerfile: ../Dockerfile
    ports:
      - "4800:4800"
    volumes:
      - ./mfe-mos:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4800
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge